### ISSUE TITLE
文本颜色问题

### ISSUE THREAD

**Issue by luzhlon** [luuman/hexo-theme-spfk#6]
文本看起来是灰色的，配合黑色的背景读起来比较费力。请问还有别的配色吗？ 我在配置文件里改过

```
highlight_style:
   on: true
   inline_code: 9  # Value: 0 - 9 可选
   code_block: 2  # Value: 0 - 4 
```

这几个选项，好像不是调节这个的。
