### ISSUE TITLE
使用gitment时总是加载失败

### ISSUE THREAD

**Issue by fuzzdb** [luuman/hexo-theme-spfk#65]
页面提示：
Error: Comments Not Initialized

除了配置
```
gitment:
  on: true
  owner: xxx
  repo: xxx
  client_id: xxxx 
  client_secret: xxx
```

还需要配置哪里？？
![qq713191958](https://user-images.githubusercontent.com/12161773/28164132-7bc1ee3c-6800-11e7-9ccb-85ffa2c88154.png)
